version: '3.8'

services:
  fraud-detection-app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/workspace
      - /workspace/.devcontainer
    environment:
      - PYTHONPATH=/workspace
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    working_dir: /workspace
    command: streamlit run app.py --server.address 0.0.0.0
    stdin_open: true
    tty: true